### ISSUE TITLE
AWS DynamoDB Setup

### ISSUE THREAD

**Issue by dineproject** [guinify/guineexamen-api#2]
#### Description
Setup AWS DynamoDB for storing exam results data.

#### Tasks
- [ ] Setup AWS credentials
- [ ] Create DynamoDB tables
- [ ] Setup indexes 
- [ ] Configure local development
- [ ] Add basic CRUD operations
- [ ] Write quick documentation
